services:
  db:
    image: postgres:14
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - redis-net

  app:
    build: ./app
    container_name: my_app
    depends_on:
      - db
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    networks:
      - redis-net

  redis:
    image: redis:7
    container_name: my_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - redis-net

  redis_commander:
    image: rediscommander/redis-commander
    container_name: redis_commander
    restart: always
    ports:
      - "8081:8081"
    networks:
      - redis-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - redis-net

volumes:
  postgres_data:
  pgadmin_data:

networks:
  redis-net:
    driver: bridge
